controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

products_list:
    path: /products
    controller: App\Controller\HomeController::showproducts
